### ISSUE TITLE
How to import idb inside ServiceWorker?

### ISSUE THREAD

**Issue by MohammedSaberMohammed** [jakearchibald/idb#183]
Hello Everyone, I'm trying to include idb in my service worker file but i got a lot of errors, i tried to import it like that:
 importScripts("https://github.com/jakearchibald/idb/blob/master/build/cjs/index.js");
`Also`
importScripts("https://github.com/jakearchibald/idb/blob/master/build/esm/index.js");
`Also`
importScripts("https://github.com/jakearchibald/idb/blob/master/build/iife/index-min.js");
`but i got the following error :`
![Screenshot from 2020-05-25 23-57-53](https://user-images.githubusercontent.com/19964514/82845280-3066d880-9ee4-11ea-9300-ef45da1c547d.png)

`And  when I use :`
importScripts("https://cdn.jsdelivr.net/npm/idb@5.0.3/build/cjs/index.min.js");

i got an error like that:
`note: the first line is the error and the second is when I log(self)`
![Screenshot from 2020-05-26 00-11-39](https://user-images.githubusercontent.com/19964514/82845615-8c7e2c80-9ee5-11ea-9cd6-15cf3926f815.png)
 

I took a look on this question:
https://github.com/jakearchibald/idb/issues/63
this link is the only one I found it working, `why is that`?
importScripts("https://cdn.jsdelivr.net/npm/idb@4.0.5/build/iife/with-async-ittr-min.js");

1. So What should I do in order to include it ?
2. How to cache it for offline? because when I enable offline signal while importing it like this
![Screenshot from 2020-05-26 03-24-26](https://user-images.githubusercontent.com/19964514/82851556-7467d680-9f00-11ea-8161-0623c6615fc0.png)
`i got the following error`
![Screenshot from 2020-05-26 03-25-39](https://user-images.githubusercontent.com/19964514/82851623-9bbea380-9f00-11ea-8d68-5399863f36e4.png)

i don't understand why it doesn't work even if i cache it's response? 

Thanks in advance.

**Comment by jakearchibald** [comment]
You'd typically use a bundler tool like Rollup or webpack to use this library, but [as detailed in the installation section](https://github.com/jakearchibald/idb#installation), you can use `https://unpkg.com/idb?module`.

**Comment by mangelozzi** [comment]
> You'd typically use a bundler tool like Rollup or webpack to use this library, but [as detailed in the installation section](https://github.com/jakearchibald/idb#installation), you can use `https://unpkg.com/idb?module`.

Thanks for the library. While I have been researching service workers and I have come across your name a few times. You are kind of like a service worker celebrity on github/stack overflow. I am using it since google recommends it while following this guide (and because the library sounds great): https://developers.google.com/web/ilt/pwa/working-with-indexeddb

The phrase `https://unpkg.com/idb?module` no longer exists in the [installation section](https://github.com/jakearchibald/idb#installation). I opened <https://github.com/jakearchibald/idb#installation> and it has an import section itself, which confuses me because thats what raises the error.

Could you give a high level description of what the bundler does to use this module? (that way I can mimic it).
I am guessing it just takes <https://cdn.jsdelivr.net/npm/idb@7/build/umd.js> and inlines it before the service worker file. Then one uses the global `idb` object.

**Comment by jakearchibald** [comment]
I think https://rollupjs.org/guide/en/ gives a good overview of what a bundler is and how it works.

The other option is described in https://github.com/jakearchibald/idb#directly-in-a-browser
