### ISSUE TITLE
Interface 'TypedDOMStringList<T>' incorrectly extends interface 'DOMStringList'

### ISSUE THREAD

**Issue by thisisamir98** [jakearchibald/idb#327]
trying to build this library with typescript version 5.0.4 I get this error:

```shell
node_modules/idb/build/entry.d.ts:121:18 - error TS2430: Interface 'TypedDOMStringList<T>' incorrectly extends interface 'DOMStringList'.
  The types returned by '[Symbol.iterator]()' are incompatible between these types.
    Type 'IterableIterator<T>' is missing the following properties from type 'ArrayIterator<string>': map, filter, take, drop, and 9 more.

121 export interface TypedDOMStringList<T extends string> extends DOMStringList {
                     ~~~~~~~~~~~~~~~~~~


Found 1 error in node_modules/idb/build/entry.d.ts:121

```

After some investigations I found out in the newer versions of javascript the type for iteration on DOMStringList has been officially added.

https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.iterable.generated.d.ts#L80-L82

```typescript
interface DOMStringList {
    [Symbol.iterator](): ArrayIterator<string>;
}
```

now updating 

```typescript
export interface TypedDOMStringList<T extends string> extends DOMStringList {
  contains(string: T): boolean;
  item(index: number): T | null;
  [index: number]: T;
  [Symbol.iterator](): IterableIterator<T>;
}
```

to 

```typescript
export interface TypedDOMStringList<T extends string> extends DOMStringList {
  contains(string: T): boolean;
  item(index: number): T | null;
  [index: number]: T;
  [Symbol.iterator](): ArrayIterator<string>;
}
```

breaks your library because typescript version 4.8.3 and it does not have `ArrayIterator` type.

Trying to fix it I found out that removing this line:

https://github.com/jakearchibald/idb/blob/main/src/entry.ts#L261

```typescript
  [Symbol.iterator](): IterableIterator<T>;
```

does not break your library and i'm still able to build it successfully, 

Could you investigate this? if it's possible I can open a PR to remove that line.

**Comment by jimtendo** [comment]
I have also hit this issue.

For me, downgrading Typescript to [5.5.4](https://www.npmjs.com/package/typescript/v/5.5.4) seems to have worked, so I suspect the amended interface is added from V5.6 upwards.

**Comment by item4** [comment]
any update yet?

**Comment by jimtendo** [comment]
@jakearchibald any chance of getting @thisisamir98 's suggestion above in? If you're not confident that approach works (e.g. breaks backwards compat), I'm happy to look into it further on my end and see if I can find something that will work and retain backwards compat.

**Comment by jakearchibald** [comment]
Thanks for the ping on this. There's been an issue with my github notifications recently so I missed it.

**Comment by jakearchibald** [comment]
[Here's the code in the TypeScript playground](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&strictBuiltinIteratorReturn=true&ts=5.7.2&filetype=d.ts#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgFQE8xgATAEQHkBZAZRimQHMAZBAZxgB585RUkpdnE6MkTAHx8QAoXCp0GzNpzgBvAFBxtcbBBSZk7ABSjmALgIBKSwCMIEADbBMSANxadCVAFtjyUlBLJABXH1s0GwI4AB84UMdHDx04AG0AoPiwiKgAXUt8ZJ1U2kJwpwA6bzRMGGhc4yiASVQoTFtnFpq6qB4JDwBfIA). I haven't found a combination that fails.

**Comment by jimtendo** [comment]
@jakearchibald I did some more research on this and I'm very sorry for taking up your time - it turns out this was our fault (a misconfig that works on previous TS versions).

I'm not sure on the exact version of Typescript where this becomes necessary (I reverted to V5.5.4 as a workaround above), but on newer versions (e.g. 5.7.2), it's required that we add the `dom` lib to our Typescript config. E.g.

```
{
  "compilerOptions": {
    "outDir": "./dist",
    "rootDir": "./src",
    "paths": {
      "~/*": [
        "./*"
      ]
    },
    "lib": [
      "dom" // <------- This must be added!
    ]
  }
}
```

Without that, newer versions of Typescript will fail while building `idb` with the error:

```
Interface 'TypedDOMStringList<T>' incorrectly extends interface 'DOMStringList'.
        The types returned by '[Symbol.iterator]()' are incompatible between these types.
          Type 'IterableIterator<T>' is missing the following properties from type 'ArrayIterator<string>': map, filter, take, drop, and 9 more.
```

(Sorry for the repetition, just trying to make it easy for people to search that error as I suspect it's probably pertinent to some other packages)

**Comment by jakearchibald** [comment]
Huh, I wonder what changed in TypeScript land that means this now fails.

Anyway, thanks for digging into this.

**Comment by wbrawner** [comment]
In my case, I already had `"dom"` in the `"lib"` list, but I also had `"dom.iterable"`. Removing the latter solved the issue for me.

**Comment by danieleformichelli** [comment]
I have `dom` and I don't have `dom.iterable`, but I'm still getting the error and it looks like the type from `dom.iterable` is picked up, does anyone have any idea of what might be wront? 🙏

**Comment by jakearchibald** [comment]
If you can create a minimal example of the issue, I can take a look.

**Comment by 7sDream** [comment]
@jakearchibald 

Add dom and dom.iterable into libs will cause the error: [minmal example playground](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&strictBuiltinIteratorReturn=true&lib=lib.esnext.d.ts%2Clib.dom.d.ts%2Clib.dom.iterable.d.ts&ts=5.7.2&filetype=d.ts#code/PTAEAEBsEsCMC5QFMDOA7JAPALgGgCYD2AtgSQHTTZIBOAhrJEgFBYAOhN2o0a1NAMzoBjJKAAqATzZJ8AEQDyAWQDK2GrwDmAGWgpsAHnHIcSNPhSh9GtJoB8J6ucuLV6rbv2gA3s1D-QYUI+Ol4UAAprLURxAEpEWEJCJjo0AG4-AKokYnDefCxENABXYlhaeIlQAB9QEshIDIDQAG18wrrS8poAXRimgJaVSTLkyn46bE4e8MqASQnGJAXaSc4jOwyAXyA).

**Comment by kamranayub** [comment]
Yes, I ran into this too, and it came from the default `react-ts` Vite template (as of this comment date).

Notably, it does not occur with anything _other_ than `esnext`. When I tried to update my Vite `tsconfig.json` to target and use `esnext`, that's when I ran into this. They also include `skipLibCheck: true` which also bypasses this issue (i.e. tsc ignores the error because it comes from `node_modules`).

[Example playground](https://www.typescriptlang.org/play/?noUncheckedIndexedAccess=true&allowUnusedLabels=true&noUnusedLocals=true&noUnusedParameters=true&useUnknownInCatchVariables=true&exactOptionalPropertyTypes=true&noFallthroughCasesInSwitch=true&noImplicitOverride=true&noPropertyAccessFromIndexSignature=true&strictBuiltinIteratorReturn=true&lib=lib.es2020.d.ts%2Clib.dom.d.ts%2Clib.dom.iterable.d.ts&ts=5.7.2&filetype=d.ts#code/PTAEAEBsEsCMC5QFMDOAmADJgNAEwPYC2eRAdNAC5IBOAhrJEgFBIAeADvtRaNAHZVqAM1oBjJKAAqAT3ZJcAEQDyAWQDKFavwDmAGWgoKAHknJWVPrhShDWvtoB8Zi1dDL1mnfsOgA3k1BA0FF8AVp+FAAKWx1ESQBKRFh8fEZaPgBuAKDKJEJI-lw2RD4AV0JYGkSpUAAfUDLISCyg0ABtQuKG8srqAF04lqC2tWkK1PJBWgouPsjqgEkphiQlmmmuEwcsgF8gA) where it _works_ with `dom.iterable` and `es2020`

**Comment by jimtendo** [comment]
I thought adding the `dom` lib would fix this as per here (and it did on one of my projects):

https://github.com/jakearchibald/idb/issues/327#issuecomment-2545477498

... but I actually bumped into it again on another project and, even when I add that, I still appear to get this error (using Typescript V5.8.2).

Can confirm, as with kamranayub above, that  `es2022` works fine for me (no `dom` lib needed) - `esnext` does not though.

I'm wondering if the approach in the OP (removing `[Symbol.iterator](): IterableIterator<T>;`)  might be the better approach? We're extending from `TypedDOMStringList` and the type of the iterator is indeed a `string`, so it might not be appropriate to allow a generic `T` in this case?

https://github.com/microsoft/TypeScript/blob/main/src/lib/dom.iterable.generated.d.ts#L76
